name: "Build APK"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
        # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        # 2. Install Dependencies and Setup Environment
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build libgtk-3-dev unzip wget

        # 3. Set Up Java 17
      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

        # 4. Install and Setup Flutter
      - name: Install Flutter
        run: |
          git clone --branch stable https://github.com/flutter/flutter.git
          echo "export PATH=\$PATH:$(pwd)/flutter/bin" >> $GITHUB_ENV
        shell: bash

      # 5. Verify Flutter Path and Run flutter doctor
      - name: Verify Flutter Installation
        run: |
          source $GITHUB_ENV
          flutter doctor

        # 6. Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: |
          source $GITHUB_ENV
          flutter pub get

        # 7. Build APK
      - name: Build APK
        run: |
          source $GITHUB_ENV
          flutter build apk --release

        # 8. Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: build/app/outputs/flutter-apk/app-release.apk
