name: "Build APK"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Dependencies
      - name: Install Required Packages
        run: |
          apt-get update -y > /dev/null
          apt-get install -y clang cmake ninja-build libgtk-3-dev nano > /dev/null

      # 3. Clone Flutter
      - name: Clone Flutter
        run: |
          git clone --quiet https://github.com/flutter/flutter.git -b stable

      # 4. Set Up Android SDK
      - name: Set Up Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9862592_latest.zip > /dev/null
          mkdir -p Android/Sdk
          unzip -q commandlinetools-linux-9862592_latest.zip -d Android/Sdk
          export ANDROID_HOME=$(pwd)/Android/Sdk
          export PATH="$PATH:$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools"
          export PATH="$PATH:$(pwd)/flutter/bin"
          
          # Accept licenses and install packages
          yes | sdkmanager --sdk_root=${ANDROID_HOME} "tools" > /dev/null
          yes | sdkmanager --update --sdk_root=${ANDROID_HOME} > /dev/null
          sdkmanager --list --sdk_root=${ANDROID_HOME} > /dev/null
          yes | sdkmanager "platform-tools" "platforms;android-31" "tools" "cmdline-tools;latest" "build-tools;31.0.0" --sdk_root=${ANDROID_HOME} > /dev/null
          yes | sdkmanager --licenses --sdk_root=${ANDROID_HOME} > /dev/null

      # 5. Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: |
          export PATH="$PATH:$(pwd)/flutter/bin"
          flutter pub get

      # 6. Build APK
      - name: Build APK
        run: |
          export PATH="$PATH:$(pwd)/flutter/bin"
          flutter build apk --release

      # 7. Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: build/app/outputs/flutter-apk/app-release.apk
