name: "Build APK"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
        # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        # 2. Install Dependencies and Setup Environment
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build libgtk-3-dev unzip wget

        # 3. Set Up Java 17
      - name: Set Up Java 17
        run: |
          sudo apt-get install -y openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          javac -version
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

        # 4. Setup Android SDK
      - name: Setup Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          unzip -q commandlinetools-linux-10406996_latest.zip -d $HOME/Android/Sdk/cmdline-tools
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "cmdline-tools;latest"

        # 5. Install Flutter
      - name: Install Flutter
        run: |
          git clone --branch stable https://github.com/flutter/flutter.git
          export PATH="$PATH:$(pwd)/flutter/bin"
          flutter doctor

        # 6. Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

        # 7. Build APK
      - name: Build APK
        run: flutter build apk --release

        # 8. Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: build/app/outputs/flutter-apk/app-release.apk
